name: Database Migration

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
    - develop
    paths:
    - 'prs/prs-rest-server/src/main/resources/db/migration/**' # Only trigger on migration file changes

jobs:
  database-migration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Maven settings.xml
      run: |
        mkdir -p ~/.m2
        echo "<settings>
                <servers>
                  <server>
                    <id>github-webank</id>
                    <username>${{ github.actor }}</username>
                    <password>${{ secrets.WEBANK_ACCESS_TOKEN }}</password>
                  </server>
                </servers>
              </settings>" > ~/.m2/settings.xml

    # 1. Authenticate to your cluster
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}

    - name: Set up kubeconfig
      uses: aws-actions/amazon-eks-login@v1
      with:
        cluster-name: ${{ vars.EKS_CLUSTER_NAME }}
        region: ${{ vars.AWS_REGION }}
    # 2. Trigger the Flyway Job from devop repo
    - name: Apply Flyway Job manifest
      run: |
        kubectl apply -f https://github.com/ADORSYS-GIS/webank-devops/blob/feat/Implement_flyway_migration/charts/webank-prs/templates/flyway-migration-job.yaml

    - name: Wait for Flyway migration to finish
      run: |
        kubectl wait --for=condition=complete \
          --timeout=300s job --selector=job-name=webank-prs-flyway-migration

    # 3. Clean up old jobs
    - name: Cleanup Flyway jobs
      if: always()
      run: |
        kubectl delete jobs --selector=job-name=webank-prs-flyway-migration || true

    # 4. Verify migration status
    - name: Check migration logs
      run: |
        kubectl logs job/webank-prs-flyway-migration 
