name: Build and Push Flyway Image

on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Maven settings.xml
      run: |
        mkdir -p ~/.m2
        echo "<settings>
                <servers>
                  <server>
                    <id>github-webank</id>
                    <username>${{ github.actor }}</username>
                    <password>${{ secrets.WEBANK_ACCESS_TOKEN }}</password>
                  </server>
                </servers>
              </settings>" > ~/.m2/settings.xml

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build Flyway image
      run: |
        docker build -t ghcr.io/adorsys-gis/webank-prs:flyway-${{ github.sha }} -t ghcr.io/adorsys-gis/webank-prs:flyway-latest -f Dockerfile.flyway .

    - name: Push Flyway image to GHCR
      run: |
        docker push ghcr.io/adorsys-gis/webank-prs:flyway-${{ github.sha }}
