name: Build and Push Flyway Image

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: adorsys-gis/webank-prs

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write # Required for SLSA provenance

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: "0"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - id: string
      name: Lowercase the name
      uses: AsZc/change-string-case-action@v6
      with:
        string: ${{ env.IMAGE_NAME }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}
        tags: |
          type=raw,value=flyway-${{ github.sha }}
          type=raw,value=flyway-latest
          type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Africa/Lagos'}},prefix=flyway-
          type=sha,format=long,prefix=flyway-

    - name: Cache Docker layers
      uses: actions/cache@v4
      if: always()
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-flyway-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-flyway-

    - name: Build and push Flyway image
      uses: docker/build-push-action@v6
      # if: github.event_name != 'pull_request'
      with:
        context: .
        file: Dockerfile.flyway
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        # provenance: true
        # sbom: true
